/**AMBITO DE LAS EXCEPCIONES**/

-- LA EXCEPCIONES SE TRATAN EN EL HABITO
DECLARE
    REG_MAX EXCEPTION;
    REGN NUMBER;
    REGT VARCHAR2(200);
BEGIN
    REGN := 101;
    REGT := 'ASIA CENTRAL';
    
    DECLARE
        --REG_MAX EXCEPTION;
    BEGIN
        IF REGN > 100 THEN
            RAISE REG_MAX;
        ELSE
            INSERT INTO REGIONS VALUES (REGN,REGT);
            COMMIT;
        END IF;
    END;
EXCEPTION
    WHEN REG_MAX THEN
        DBMS_OUTPUT.PUT_LINE('la region no puede ser mayor de 100.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INDEFINIDO');
END;