SET SERVEROUTPUT ON
/**
    EL AMBITOS DE LAS VARIABLE 
    LA VARIABLE DEL PADRE SE PUEDEN USAR EN EL HIJO
    PERO VICEVERSA NO ES POSIBLE.
**/
DECLARE 
    X NUMBER := 20; --GLOBAL
    Z NUMBER := 30;
BEGIN
    DBMS_OUTPUT.PUT_LINE('X := '||X);
    DECLARE
        X NUMBER := 10; --LOCAL
    BEGIN
        DBMS_OUTPUT.PUT_LINE('X := '||X);
        DBMS_OUTPUT.PUT_LINE('Z := '||Z);
    END;
END;