/**COMANDO CASE**/
--EJEMPLO 1
SET SERVEROUTPUT ON
DECLARE
    V1 CHAR (1);
BEGIN
    V1 := 'B';
    
    CASE V1
        WHEN 'A' THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
        WHEN 'B' THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
        WHEN 'C' THEN DBMS_OUTPUT.PUT_LINE('GOOD');
        WHEN 'D' THEN DBMS_OUTPUT.PUT_LINE('FAIR');
        WHEN 'F' THEN DBMS_OUTPUT.PUT_LINE('POOR');
        ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH VALUE ');
    END CASE;

END;

--EJEMPLO 2
SET SERVEROUTPUT ON
DECLARE
    V1 NUMBER;
BEGIN
    V1 := 50;
    
    CASE V1
        WHEN 10 THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
        WHEN 20 THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
        WHEN 30 THEN DBMS_OUTPUT.PUT_LINE('GOOD');
        WHEN 40 THEN DBMS_OUTPUT.PUT_LINE('FAIR');
        WHEN 50 THEN DBMS_OUTPUT.PUT_LINE('POOR');
        ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH VALUE ');
    END CASE;
END;

--EJEMPLO 3
SET SERVEROUTPUT ON
DECLARE
    V1 VARCHAR2(20);
BEGIN
    V1 := 'FAIR';
    
    CASE V1
        WHEN 'EXCELLENT' THEN DBMS_OUTPUT.PUT_LINE('A');
        WHEN 'VERY GOOD' THEN DBMS_OUTPUT.PUT_LINE('B');
        WHEN 'GOOD' THEN DBMS_OUTPUT.PUT_LINE('C');
        WHEN 'FAIR' THEN DBMS_OUTPUT.PUT_LINE('D');
        WHEN 'POOR' THEN DBMS_OUTPUT.PUT_LINE('F');
        ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH VALUE ');
    END CASE;
END;
