/** SEARCHED CASE**/

SET SERVEROUTPUT ON
DECLARE 
    BONUS NUMBER;
BEGIN
    BONUS := 100;
    
    CASE
        WHEN BONUS > 500 THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
        WHEN BONUS <= 500 AND BONUS > 250 THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
        WHEN BONUS <= 250 AND BONUS > 100 THEN DBMS_OUTPUT.PUT_LINE('GOOD');
        ELSE DBMS_OUTPUT.PUT_LINE('POOR¡¡¡');
    END CASE;

END;