/**COMPROBAR EL ESTADO DE LOS TRIGGERS**/

SELECT OBJECT_NAME , OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'TRIGGER';

--  COMPILAR TRIGGER
ALTER TRIGGER TR3_REGION COMPILE;

--  MUESTRA LOS ERRORES
SELECT * FROM USER_ERRORS;

--  DESACTIVA EL TRIGGER
ALTER TRIGGER TR3_REGION DISABLE;

--  ACTIVA EL TRIGGER
ALTER TRIGGER TR3_REGION ENABLE;

--  DESCRIPCION DE LOS TRIGGERS
DESC USER_TRIGGERS;

--  VER LOS TRIGGERS
SELECT TRIGGER_NAME , STATUS
FROM USER_TRIGGERS;


