/**CONTROLAR EL TIPO DE EVENTO - TRIGGER**/

CREATE OR REPLACE TRIGGER TR2_REGION
BEFORE INSERT OR UPDATE OR DELETE
ON REGIONS
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG_TABLE VALUES ('INSERCION',USER);
    END IF;
    IF UPDATING('REGION_ID') THEN
        INSERT INTO LOG_TABLE VALUES ('UPDATE DE REGION_ID',USER);
    END IF;
     IF UPDATING ('REGION_NAME') THEN
        INSERT INTO LOG_TABLE VALUES ('UPDATE DE REGION_NAME',USER);
    END IF;
    IF DELETING THEN
        INSERT INTO LOG_TABLE VALUES ('DELETE',USER);
    END IF;
END;

-- PROBAR EL TRIGGER
INSERT INTO REGIONS VALUES (1050,'REGION 6');

UPDATE REGIONS SET REGION_ID = 1049 WHERE REGION_ID = 1050;