/**CREAR TRIGGERS CON EVENTOS MULTIPLES**/

CREATE OR REPLACE TRIGGER TR1_REGION
BEFORE INSERT OR UPDATE OR DELETE ON REGIONS
BEGIN
    IF USER <> 'HR' THEN
        RAISE_APPLICATION_ERROR(-20000,'SOLO HR PUEDE TRABAJAR EN REGIONS');
    END IF;
END;

-- TRABAJAR POR COLUMNAS
CREATE OR REPLACE TRIGGER TR1_REGION_NAME
BEFORE INSERT OR UPDATE OF REGION_NAME OR DELETE 
ON REGIONS
BEGIN
    IF USER <> 'HR' THEN
        RAISE_APPLICATION_ERROR(-20000,'SOLO HR PUEDE TRABAJAR EN REGIONS');
    END IF;
END;

--LLAMAR EL TRIGGER
UPDATE REGIONS SET REGION_NAME = 'HOLAA' WHERE REGION_ID = 1000;
