/**CREAR EL CUERPO DEL PACKETE**/
CREATE OR REPLACE PACKAGE PACK1
IS  
   PROCEDURE CONVERT (NAME VARCHAR2,CONVERSION_TYPE CHAR);
END;
/

-- LA CABEZERA Y EL CUERPO SE HACEN POR SEPARADO

CREATE OR REPLACE PACKAGE BODY PACK1
IS
    FUNCTION UP (NAME VARCHAR2)
        RETURN VARCHAR2
    IS 
    BEGIN
        RETURN UPPER (NAME);
    END UP;

    FUNCTION DO (NAME VARCHAR2)
        RETURN VARCHAR2
    IS
    BEGIN
        RETURN LOWER (NAME);
    END DO;

PROCEDURE CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR)
IS 
BEGIN
    IF CONVERSION_TYPE = 'U' OR CONVERSION_TYPE = 'u'  THEN
        DBMS_OUTPUT.PUT_LINE(UP(NAME));
    ELSIF CONVERSION_TYPE = 'L' OR CONVERSION_TYPE = 'l' THEN
        DBMS_OUTPUT.PUT_LINE(DO(NAME));
    ELSE
        DBMS_OUTPUT.PUT_LINE('EL PARAMETRO DEBE SER U O L');
    END IF;
END CONVERT;

END PACK1;



----    LLAMAR AL PACKAGE
SET SERVEROUTPUT ON
BEGIN
    PACK1.CONVERT('MOISES VAlencia','u');
END;
