/**CICLO DE VIDA DE UN CURSOR**/

/**CREAR UN CURSOR**/

DECLARE
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN
    OPEN C1; -- ABRE EL CURSOR
    FETCH C1 INTO V1; --LEER EL CURSOR   
    DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    FETCH C1 INTO V1;    
    DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    CLOSE C1; --CERRAR EL CURSOR
    
END;