/**CREAR LA CABEZERA DE UN PAQUETE**/

CREATE OR REPLACE PACKAGE PACK1
IS
    V1 NUMBER := 0;
    V2 VARCHAR2(100);
END;


-- ACCEDER A LOS DATOS DE PACKETE
SET SERVEROUTPUT ON
BEGIN
    PACK1.V1 := 100;
    PACK1.V2 := 'HOLA';
    DBMS_OUTPUT.PUT_LINE(PACK1.V1);
    DBMS_OUTPUT.PUT_LINE(PACK1.V2);
END;


--AMBITO DE LAS VARIABLES
/**
    LAS VARIABLES DEL PAQUETE SOLO SE INICIALIZAN UNA VEZ
    DURANTE LA SESION DEL USUARIO , POR LO TANTO SE MANTIENEN EL VALOR QUE VALLAN TOMANDO
    CADA VARIABLE.
**/

--EJECUTAR PAQUETE
SET SERVEROUTPUT ON
BEGIN
    PACK1.V1 := PACK1.V1 + 10;
    DBMS_OUTPUT.PUT_LINE(PACK1.V1);
    
END;