/**IMPEDIR OPERACIONES CON TRIGGER**/

CREATE OR REPLACE TRIGGER TR1_REGIONS 
BEFORE INSERT ON REGIONS 
BEGIN
    IF USER <> 'HR' THEN
        RAISE_APPLICATION_ERROR(-20000,'SOLO EL USUARIO HR PUEDE INSERTAR EN REGIONS');
    END IF;
END;

--  USAR EL TRIGGER
INSERT INTO REGIONS VALUES (100450,'TEST REGIONS A');