/**INTRODUCCION A LOS CURSORES**/

--IMPLICITOS 
-- +SELECT

--EXPLICITOS

/**
SQL%ISOPEN --FALSE
SQL%FOUND
SQL%NOTFOUND
SQL%ROWCOUNT
**/
DECLARE
    X NUMBER;
BEGIN
    --
    UPDATE TEST SET C2 = 'PPPPP' WHERE C1 = 10;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ENCONTRDO');
    END IF;
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO ENCONTRDO');
    END IF;
    
    
    SELECT C1 INTO X FROM TEST WHERE C1 = 1000;
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ENCONTRDO');
    END IF;
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO ENCONTRDO');
    END IF;
END;