/**INTRODUCCION A LAS EXCEPCIONES**/

--TIPOS DE EXCEPCIONES
--  ORACLE (PROPIAS DE ORACLE)
--  USAURIO (LAS QUE UNO CREA)


/**SINTAXIS DE LAS EXCEPCIONES**/
SET SERVEROUTPUT ON
DECLARE 
    EMPL EMPLOYEES%TYPE;
BEGIN
    SELECT * INTO EMPL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
    DBMS_OUTPUT.PUT_LINE(EMPL.FIRST_NAME);
EXCEPTION
    WHEN EX1 THEN
        NULL;
    WHEN EX2 THEN
        NULL;
    WHEN OTHERS THEN
        NULL;
END;
/

/**EXCEPCIONES PREDEFINIDAS**/
SET SERVEROUTPUT ON
DECLARE 
    EMPL EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO EMPL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
    DBMS_OUTPUT.PUT_LINE(EMPL.FIRST_NAME);
EXCEPTION
-- NO_DATA_FOUND
-- TOO_MANY_ROWS
-- ZERO_DIVIDE
-- DUP_VAL_ON_INDEX

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR, EMPLEADO INSEXISTENTE');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('DEMASIADOS EMPLEADOS');
    WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('ERROR INDEFINIDO');
END;
/


/**EXCEPCIONES NO PREDEFINIDAS**/

DECLARE
    MI_EXCEP EXCEPTION;
    PRAGMA EXCEPTION_INIT(MI_EXCEP, -937);
    V1 NUMBER;
    V2 NUMBER;
BEGIN
    SELECT EMPLOYEE_ID, SUM(SALARY) INTO V1,V2 FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(V1);
EXCEPTION
    WHEN MI_EXCEP THEN
        DBMS_OUTPUT.PUT_LINE('FUNCION DE GRUPO INCORRECTA');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INDEFINDO');
END;
 






