/**FUNCIONES**/


-- CREACION DE LA FUNCION
CREATE OR REPLACE FUNCTION CALC_TAX_F
    (EMPL IN EMPLOYEES.EMPLOYEE_ID%TYPE,
        T1 IN NUMBER)
RETURN NUMBER
IS  
    TAX NUMBER := 0;
    SAL NUMBER := 0;
BEGIN
    IF T1 < 0 OR T1 > 60 THEN
        RAISE_APPLICATION_ERROR (-20000, 'EL PORCENTAJE DEBE ESTAR ENTRE 0 Y 60');
    END IF;
    SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = EMPL;
    TAX := SAL * T1/100;
    RETURN TAX;
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('NO EXISTE EL EMPLEADO');
END;
/

-- LLAMAR A LA FUNCION
SET SERVEROUTPUT ON
DECLARE 
    A NUMBER;
    B NUMBER;
    R NUMBER;
BEGIN
    A := 120;
    B := 10;
    R := CALC_TAX_F(A,B);
    DBMS_OUTPUT.PUT_LINE('R = '||R);
END;