/**PARAMETROS DE TIPO IN**/

-- CREACION DEL PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE CALC_TAX
(EMPL IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    T1 IN NUMBER)
IS
    TAX NUMBER := 0;
    SAL NUMBER := 0;
BEGIN
    IF T1 < 0 OR T1 > 60 THEN
        RAISE_APPLICATION_ERROR(-20000,'EL PORCENTAJE DEBE ESTAR ENTRE 0 Y 60');
    END IF;
    -- LA VARIABLE T1 SOLO SE PUEDE USAR COMO LECTURA.
    SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = EMPL;
    TAX := SAL * T1/100;
    DBMS_OUTPUT.PUT_LINE('SALARY : '||SAL);
    DBMS_OUTPUT.PUT_LINE('TAX : '||TAX);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE EL EMPLEADO');
END;
/
--  LLAMADA DEL PROCEDIMIENTO
SET SERVEROUTPUT ON
DECLARE
    A NUMBER;
    B NUMBER;
BEGIN
    A := 120;
    B := 500;
    CALC_TAX(A,B);
END;