/**PARAMETROS DE TIPO OUT**/

--  CREACION DEL PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE CALC_TAX_OUT
(EMPL IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    T1 IN NUMBER,
    R1 OUT NUMBER)
IS
    SAL NUMBER := 0;
BEGIN 
      IF T1 < 0 OR T1 > 60 THEN
        RAISE_APPLICATION_ERROR(-20000,'EL PORCENTAJE DEBE ESTAR ENTRE 0 Y 60');
    END IF;
    SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = EMPL;
    R1 := SAL * T1/100;
    DBMS_OUTPUT.PUT_LINE('SALARY : '||SAL);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE EL EMPLEADO');
END;
/

-- LLAMAR AL PROCEDIMIENTO
SET SERVEROUTPUT ON
DECLARE
    A NUMBER;
    B NUMBER;
    R NUMBER;
BEGIN
    A := 120;
    B := 10;
    R := 0;
    CALC_TAX_OUT(A,B,R);
    DBMS_OUTPUT.PUT_LINE('R = '||R);
END;