/**PARAMETROS DE TIPO IN-OUT**/


--  CREACION DEL PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE CALC_TAX_IN_OUT
(EMPL IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    T1 IN OUT NUMBER)
IS
    SAL NUMBER := 0;
BEGIN 
    IF T1 < 0 OR T1 > 60 THEN
        RAISE_APPLICATION_ERROR(-20000,'EL PORCENTAJE DEBE ESTAR ENTRE 0 Y 60');
    END IF;
    SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = EMPL;
    DBMS_OUTPUT.PUT_LINE('T1 : '||T1);
    T1 := SAL * T1/100;
    DBMS_OUTPUT.PUT_LINE('SALARY : '||SAL);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE EL EMPLEADO');
END;
/

-- LLAMAR AL PROCEDIMIENTO
SET SERVEROUTPUT ON
DECLARE
    A NUMBER;
    B NUMBER;
BEGIN
    A := 120;
    B := 10;
    CALC_TAX_IN_OUT(A,B);
    DBMS_OUTPUT.PUT_LINE('B = '||B);
END;