/**PRACTICA CON BUCLES**/
SET SERVEROUTPUT ON

--PRACTICA 1
DECLARE
    NUMERO NUMBER := 3;
    I NUMBER := 1;
    ILOOP NUMBER := 1;
BEGIN

    -- CICLO FOR
    DBMS_OUTPUT.PUT_LINE('CICLO FOR');
    FOR I IN 1..10 LOOP
          DBMS_OUTPUT.PUT_LINE(I||' X '||NUMERO||' = '|| I * NUMERO);
    END LOOP;
    
    -- CICLO WHILE
    DBMS_OUTPUT.PUT_LINE('CICLO WHILE');
    WHILE I <= 10  LOOP
        DBMS_OUTPUT.PUT_LINE(I||' X '||NUMERO||' = '|| I * NUMERO);
        I := I + 1;
    END LOOP;
    
    --CICLO LOOP
    DBMS_OUTPUT.PUT_LINE('CICLO LOOP'); 
    LOOP
        DBMS_OUTPUT.PUT_LINE(ILOOP||' X '||NUMERO||' = '|| ILOOP * NUMERO);
        ILOOP := ILOOP + 1;
        EXIT WHEN ILOOP = 11;
    END LOOP;
END;


--PRACTICA 2
DECLARE
    TEXTO VARCHAR2(100);
    TEXTO_NUEVO VARCHAR2(100) := '';
BEGIN
    TEXTO := 'BIENVENIDOS';
    --DBMS_OUTPUT.PUT_LINE(LENGTH(TEXTO));
    FOR I IN REVERSE 1..LENGTH(TEXTO) LOOP
        --DBMS_OUTPUT.PUT_LINE(SUBSTR(TEXTO,I,1));
        TEXTO_NUEVO := TEXTO_NUEVO|| SUBSTR(TEXTO,I,1); 
    END LOOP;
     DBMS_OUTPUT.PUT_LINE(TEXTO_NUEVO);
END;


--PRACTICA 3
DECLARE
    TEXTO VARCHAR2(100);
    TEXTO_NUEVO VARCHAR2(100) := '';
BEGIN
    TEXTO := 'BIENVENXIDOS';
    --DBMS_OUTPUT.PUT_LINE(LENGTH(TEXTO));
    FOR I IN REVERSE 1..LENGTH(TEXTO) LOOP
        --DBMS_OUTPUT.PUT_LINE(SUBSTR(TEXTO,I,1));
        EXIT WHEN ((SUBSTR(TEXTO,I,1) = 'x') OR  (SUBSTR(TEXTO,I,1) = 'X')) ;
        TEXTO_NUEVO := TEXTO_NUEVO|| SUBSTR(TEXTO,I,1); 
    END LOOP;
     DBMS_OUTPUT.PUT_LINE(TEXTO_NUEVO);
END;

--PRACTICA 4
DECLARE
    NOMBRE VARCHAR2(100);
    TEXTO_NUEVO VARCHAR2(100) := '';
BEGIN
    NOMBRE := 'MOISES';
    FOR I IN 1..LENGTH(NOMBRE) LOOP
        TEXTO_NUEVO := TEXTO_NUEVO||'*'; 
    END LOOP;
     DBMS_OUTPUT.PUT_LINE(TEXTO_NUEVO);
END;

--PRACTICA 5
DECLARE
    INICIO NUMBER;
    FIN NUMBER;
BEGIN
    INICIO := 2;
    FIN := 76;
    FOR I IN INICIO..FIN LOOP
        IF MOD(I,4) = 0 THEN
            DBMS_OUTPUT.PUT_LINE(I);
        END IF;    
    END LOOP;
END;

