/**PRACTICA DE COLECCIONES Y REGISTROS**/
/**
SET SERVEROUTPUT ON
DECLARE
     TYPE EMPLEADO IS RECORD
        (NAME VARCHAR2(100),
        SAL EMPLOYEES.SALARY%TYPE,
        COD_DEPT EMPLOYEES.DEPARTMENT_ID%TYPE);
        
   TYPE EMPLEADOS IS TABLE OF
        EMPLEADO%ROWTYPE
    INDEX BY PLS_INTEGER;
    
    EMPLE EMPLEADOS;
    
    NOMBRE EMPLOYEES.FIRST_NAME%TYPE;
    APELLIDO EMPLOYEES.LAST_NAME%TYPE;
BEGIN 
    FOR I IN 100..206 LOOP
        SELECT FIRST_NAME INTO NOMBRE FROM EMPLOYEES WHERE EMPLOYEE_ID = I ;
        SELECT LAST_NAME INTO APELLIDO FROM EMPLOYEES WHERE EMPLOYEE_ID = I;  
        EMPLE(I).NAME := NOMBRE||' '||APELLIDO ;
    END LOOP;
    
    FOR I IN EMPLE.FIRST..EMPLE.LAST LOOP
        DBMS_OUTPUT.PUT_LINE (EMPLE(I).NAME);
    END LOOP;
END;
**/

SET SERVEROUTPUT ON
DECLARE
  TYPE EMPL_RECORD IS RECORD 
  ( 
    NAME VARCHAR2(100),
    SAL EMPLOYEES.SALARY%TYPE,
    COD_DEPT EMPLOYEES.DEPARTMENT_ID%TYPE);
  
 
  TYPE EMPL_TABLE IS TABLE OF
      EMPL_RECORD
  INDEX BY PLS_INTEGER;
 
   cursor empleados is  select FIRST_NAME||' '||LAST_NAME, SALARY,DEPARTMENT_ID  FROM EMPLOYEES  where employee_id between 100 and 206 order by SALARY DESC; 
  
  EMPL EMPL_TABLE; 
  
  CONTADOR NUMBER:=100;
  
BEGIN
   
   FOR I in empleados  LOOP
      EMPL(CONTADOR):=I;      
      CONTADOR:=CONTADOR+1;
   END LOOP;
  
   FOR I IN EMPL.FIRST..EMPL.LAST LOOP
     DBMS_OUTPUT.PUT_LINE(EMPL(I).NAME||' '||EMPL(I).SAL||' '||EMPL(I).COD_DEPT);
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('EL QUE MAS GANA');
   DBMS_OUTPUT.PUT_LINE(EMPL(EMPL.FIRST).NAME);
   DBMS_OUTPUT.PUT_LINE('EL QUE MENOS GANA'); 
   DBMS_OUTPUT.PUT_LINE(EMPL(EMPL.LAST).NAME);
   
   DBMS_OUTPUT.PUT_LINE('BORRAMOS LOS EMPLEADOS QUE GANEN MENOS DE 7000'); 
   DBMS_OUTPUT.PUT_LINE('ANTES');
   DBMS_OUTPUT.PUT_LINE(EMPL.COUNT);
   FOR I IN EMPL.FIRST..EMPL.LAST LOOP
     IF EMPL(I).SAL < 7000 THEN
         EMPL.DELETE(I) ;
     END IF;
   END LOOP;
      DBMS_OUTPUT.PUT_LINE('DESPUES');
   DBMS_OUTPUT.PUT_LINE(EMPL.COUNT);
  
END;