SET SERVEROUTPUT ON
DECLARE
    /*LAS CONSTANTES NO SE MODIFICAN*/
    X CONSTANT NUMBER := 10;
    /*LAS VARIABLES NOT NULL NO PUEDEN SER NULAS*/
    Z NUMBER NOT NULL :=20;
BEGIN
    DBMS_OUTPUT.PUT_LINE(Z);
    DBMS_OUTPUT.PUT_LINE(X);
END;