SET SERVEROUTPUT ON
DECLARE
    NOMBRE VARCHAR2(50) := 'moises';
    APELLIDO1 VARCHAR2(50) := 'valencia';
    APELLIDO2 VARCHAR2(50) := 'ferreira';
BEGIN
    NOMBRE := UPPER(SUBSTR(NOMBRE,1,1));
    APELLIDO1 := UPPER(SUBSTR(APELLIDO1,1,1));
    APELLIDO2 := UPPER(SUBSTR(APELLIDO2,1,1));
    DBMS_OUTPUT.PUT_LINE(NOMBRE||'.'||APELLIDO1||'.'||APELLIDO2);

END;


SET SERVEROUTPUT ON
DECLARE
    FECHA_NACIMIENTO DATE := '02/07/1990';
    DIA_NACIMIENTO VARCHAR2(10);
BEGIN
    DIA_NACIMIENTO := TO_CHAR(FECHA_NACIMIENTO,'DAY');
    DBMS_OUTPUT.PUT_LINE(DIA_NACIMIENTO);

END;