/**PRACTICA DE FUNCIONES**/


-- CREACION DE FUNCION 
CREATE OR REPLACE FUNCTION SUMA_DE_SALARIOS
    (NUM_DEPTO EMPLOYEES.DEPARTMENT_ID%TYPE, 
        NUM_EMPLEADOS OUT NUMBER)
RETURN NUMBER
IS
    SALARIOS NUMBER;
    DEPT DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
    SELECT DEPARTMENT_ID INTO DEPT FROM DEPARTMENTS WHERE DEPARTMENT_ID = NUM_DEPTO;
    
    SELECT SUM(SALARY),COUNT(SALARY) INTO SALARIOS,NUM_EMPLEADOS FROM EMPLOYEES WHERE DEPARTMENT_ID = NUM_DEPTO;
    RETURN SALARIOS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002 ,'EL DEPARATAMENTO '||DEPT||' NO EXISTE');
END;

--  LLAMAR LA FUNCION
DECLARE
    A NUMBER;
    DEPTO EMPLOYEES.DEPARTMENT_ID%TYPE;
    NUM_EMPLE NUMBER;
BEGIN
    DEPTO := 100;
    A := SUMA_DE_SALARIOS(DEPTO,NUM_EMPLE);
    DBMS_OUTPUT.PUT_LINE('SUMA DE SALARIOS DEL DEPARTAMENTO '||DEPTO||' ES : $'||A);
    DBMS_OUTPUT.PUT_LINE('EL NUMERO DE EMPLEADOS DEL DEPARTAMENTO '||DEPTO||' ES : '||NUM_EMPLE);
END;


-- CREANDO FUNCION 2
CREATE OR REPLACE FUNCTION CREAR_REGION
    (NOMBRE_REGION VARCHAR2)
RETURN NUMBER
IS 
    COD_MAX_ALTO NUMBER;
BEGIN
    SELECT MAX(REGION_ID) INTO COD_MAX_ALTO FROM REGIONS;
    COD_MAX_ALTO := COD_MAX_ALTO + 1;
    INSERT INTO REGIONS (REGION_ID,REGION_NAME) VALUES (COD_MAX_ALTO,NOMBRE_REGION);
    RETURN COD_MAX_ALTO;
END;


--  LLAMAR LA FUNCION
DECLARE
    ID_REGION NUMBER;
    NOMBRE_REGION VARCHAR2(100);
BEGIN  
    NOMBRE_REGION := 'SUDAMERICA';
    ID_REGION := CREAR_REGION(NOMBRE_REGION);
    DBMS_OUTPUT.PUT_LINE('EL ID DE REGIO ES '||ID_REGION);
END;

