/**PRACTICA EXCEPCIONES DE USUARIO**/

DECLARE
    CONTROL_REGIONES EXCEPTION;
    ID_REGION  REGIONS.REGION_ID%TYPE;
    NOMBRE_REGION REGIONS.REGION_NAME%TYPE;
BEGIN
    ID_REGION := 105;
    NOMBRE_REGION := 'AMERICA DEL SUR';
    
    IF ID_REGION > 200 THEN
        RAISE CONTROL_REGIONES;
    ELSE
        INSERT INTO REGIONS VALUES (ID_REGION,NOMBRE_REGION);
    END IF;
EXCEPTION
    WHEN CONTROL_REGIONES THEN
        DBMS_OUTPUT.PUT_LINE('CODIGO NO PERMITIDO. DEBE SER INFERIOR A 200');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
END;