/**PRACTICA CON SELECT INTO**/

-- PRACTICA 1
SET SERVEROUTPUT ON
DECLARE
    SALARIO_MAX NUMBER;
BEGIN
    SELECT --SOLO PUEDE DEVOLVER UN FILA
        MAX(SALARY) INTO SALARIO_MAX 
    FROM 
        EMPLOYEES 
    WHERE 
        DEPARTMENT_ID = 100;
    DBMS_OUTPUT.PUT_LINE('SALARIO MAXIMO : '||SALARIO_MAX);    
END;

-- PRACTICA 2
SET SERVEROUTPUT ON
DECLARE
    EMPLEADO EMPLOYEES%ROWTYPE;
BEGIN
    SELECT --SOLO PUEDE DEVOLVER UN FILA
         * INTO EMPLEADO  
    FROM 
        EMPLOYEES 
    WHERE 
       EMPLOYEE_ID = 100;
    DBMS_OUTPUT.PUT_LINE('TIPO TRABAJO : '||EMPLEADO.JOB_ID);    
END;

-- PRACTICA 3
SET SERVEROUTPUT ON
DECLARE
    DEPARTAMENTO DEPARTMENTS%ROWTYPE;
    ID_DEPARTAMENTO DEPARTMENTS.DEPARTMENT_ID%TYPE;
    CANTIDAD NUMBER;
BEGIN
    ID_DEPARTAMENTO := 100;
    SELECT 
        * INTO DEPARTAMENTO 
    FROM 
        DEPARTMENTS 
    WHERE 
        DEPARTMENT_ID = ID_DEPARTAMENTO;
        
    SELECT 
        COUNT(*) INTO CANTIDAD 
    FROM 
        EMPLOYEES 
    WHERE 
        DEPARTMENT_ID = DEPARTAMENTO.DEPARTMENT_ID;
        
    DBMS_OUTPUT.PUT_LINE('NOMBRE DEL DEPARTAMENTO : '||DEPARTAMENTO.DEPARTMENT_NAME); 
    DBMS_OUTPUT.PUT_LINE('CANTIDAD DE TRABAJADOR : '||CANTIDAD);
END;


-- PRACTICA 4
SET SERVEROUTPUT ON
DECLARE
    SALARIO_MAX NUMBER;
    SALARIO_MIN NUMBER;
    
BEGIN
    SELECT 
        MAX(SALARY) INTO SALARIO_MAX 
    FROM 
        EMPLOYEES;
    SELECT 
        MIN(SALARY) INTO SALARIO_MIN
    FROM 
        EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE('SALARIO MAXIMO : '||SALARIO_MAX); 
    DBMS_OUTPUT.PUT_LINE('SALARIO MINIMO : '||SALARIO_MIN);
    DBMS_OUTPUT.PUT_LINE('DIFERENCIA DE SALARIO : '||(SALARIO_MAX-SALARIO_MIN));
END;





