/**PRACTICA DE PROCEDIMIENTOS Y PARAMETROS**/

CREATE OR REPLACE PROCEDURE VISUALIZAR
    (NUM_DEPTO IN EMPLOYEES.DEPARTMENT_ID%TYPE,
        V_CONTEO IN OUT NUMBER)
IS
    CURSOR C1 IS SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = NUM_DEPTO;
BEGIN
    --DBMS_OUTPUT.PUT_LINE('AQUI :'||V_CONTEO);
    FOR I IN C1 LOOP
        --DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.SALARY);
        V_CONTEO := V_CONTEO + 1;
    END LOOP;
    --DBMS_OUTPUT.PUT_LINE(V_CONTEO);
END;

SET SERVEROUTPUT ON

DECLARE
    x NUMBER;
BEGIN
    X := 0;
    DBMS_OUTPUT.PUT_LINE(X);
    VISUALIZAR(60,X);
    DBMS_OUTPUT.PUT_LINE('AQUI :'||X);
END;
