/**PRACTICA CON INSERT, UPDATE Y DELETE**/

-- PRACTICA 1
DECLARE
    DEPARTAMENTO_MAYOR DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
    SELECT MAX(DEPARTMENT_ID) INTO DEPARTAMENTO_MAYOR
    FROM DEPARTMENTS;
    
    DEPARTAMENTO_MAYOR := DEPARTAMENTO_MAYOR + 10;
    
    INSERT INTO DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID,MANAGER_ID)
        VALUES (DEPARTAMENTO_MAYOR,'INFORMATICA',1000,100);
    COMMIT;
END;
/

-- PRACTICA 2
DECLARE
    ID_DEPARTAMENTO DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
    ID_DEPARTAMENTO := 280;
    UPDATE DEPARTMENTS SET LOCATION_ID = 1700 WHERE DEPARTMENT_ID = ID_DEPARTAMENTO;
END;
/

-- PRACTICA 3
DECLARE
    ID_DEPARTAMENTO DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
    ID_DEPARTAMENTO := 280;
    DELETE FROM DEPARTMENTS  WHERE DEPARTMENT_ID = ID_DEPARTAMENTO;
END;

