/**PRACTICA DE TRIGGER**/

--  PRACTICA 1
CREATE OR REPLACE TRIGGER NO_DELETE_CLERK
BEFORE DELETE
ON EMPLOYEES 
FOR EACH ROW
BEGIN
    IF :OLD.JOB_ID LIKE ('%CLERK') THEN
        RAISE_APPLICATION_ERROR(-20320,'NADA');
    END IF;
END;

--  PROBAR TRIGGER
DELETE FROM EMPLOYEES WHERE JOB_ID LIKE ('%CLERK');

--  PRACTICA 2
CREATE TABLE AUDITORIA (
USUARIO VARCHAR(50),
FECHA DATE,
SALARIO_ANTIGUO NUMBER,
SALARIO_NUEVO NUMBER);

CREATE OR REPLACE TRIGGER AUDITORIA
BEFORE INSERT
ON REGIONS
BEGIN
    INSERT INTO AUDITORIA (USUARIO, FECHA) VALUES (USER , SYSDATE);
END;

--  PROBAR EL TRIGGER
INSERT INTO REGIONS VALUES (20,'PRUEBA');
SELECT * FROM AUDITORIA;


