/**PRACTICA CON CASE**/

SET SERVEROUTPUT ON
DECLARE
    USUARIO VARCHAR2(40);
BEGIN
    USUARIO := USER;
    CASE    
        WHEN USUARIO = 'SYS' THEN DBMS_OUTPUT.PUT_LINE('ERES SUPERADMINISTRADOR');
        WHEN USUARIO = 'SYSTEM' THEN DBMS_OUTPUT.PUT_LINE('ERES UN ADMINISTRADOR NORMAL');
        WHEN USUARIO = 'HR' THEN DBMS_OUTPUT.PUT_LINE('ERES DE RECURSOS HUMANO');
        ELSE DBMS_OUTPUT.PUT_LINE('USAURIO NO AUTORIZADO');
    END CASE;
END;