SET SERVEROUTPUT ON
DECLARE
    IMPUESTO CONSTANT NUMBER := 21;
    PRECIO NUMBER(5,2);
    RESULTADO PRECIO%TYPE;
BEGIN
    PRECIO := 120.00;
    RESULTADO := ((PRECIO * IMPUESTO)/100);
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;