
/*bloque anonimo.*/
SET SERVEROUTPUT ON
DECLARE
    NAME VARCHAR2(100);
    LASTNAME VARCHAR2(100);
BEGIN
    NAME := 'MOISES';
    LASTNAME := 'VALENCIA';
    DBMS_OUTPUT.PUT_LINE(NAME);
    DBMS_OUTPUT.PUT_LINE(LASTNAME);
    DBMS_OUTPUT.PUT_LINE(NAME||' '||LASTNAME);

END;