/**VER EL CODIGO FUENTE DE UN PROCEDIMIENTO**/


-- USER OBJECTS
SELECT * FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'PROCEDURE';


--  SABER LOS DISTINTOS OBJETOS DE LA BASE DE DATOS
SELECT OBJECT_TYPE, COUNT(*) FROM USER_OBJECTS
GROUP BY OBJECT_TYPE;


--  PARA CONOCER EL CODIGO FUENTE DEL OBJETO (EN ESTE CASO UN PROCEDIMINETO)
SELECT TEXT FROM USER_SOURCE
WHERE NAME = 'PR2';