/**REECORRER UN CURSOR CON UN BUCLE FOR**/

--NORMAL
DECLARE
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN
    FOR I IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE(I.REGION_NAME);
    END LOOP;
END;

/

-- FOR CON SUBQUERIES
BEGIN
    FOR I IN (SELECT *FROM REGIONS) LOOP
        DBMS_OUTPUT.PUT_LINE(I.REGION_NAME);
    END LOOP;
END;