/**RECORRER UN CURSOR CON UN BUCLE LOOP**/

DECLARE
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN
    OPEN C1; -- ABRE EL CURSOR
    LOOP
        FETCH C1 INTO V1; --LEER EL CURSOR
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    END LOOP;
    CLOSE C1; --CERRAR EL CURSOR
    
END;