/**TRIGGER COMPUESTO**/

-- CREAR UN TRIGGER COMPOUND

CREATE OR REPLACE TRIGGER TRIGGER1 
FOR DELETE OR INSERT OR UPDATE ON REGIONS
COMPOUND TRIGGER
    BEFORE STATEMENT IS BEGIN
        INSERT INTO LOG_TABLE VALUES ('BEFORE STATEMENT',USER);
    END BEFORE STATEMENT;
    
    AFTER STATEMENT IS BEGIN
        INSERT INTO LOG_TABLE VALUES ('AFTER STATEMENT',USER);
    END AFTER STATEMENT;
    
    BEFORE EACH ROW IS BEGIN
        INSERT INTO LOG_TABLE VALUES ('BEFORE EACH ROW',USER);
    END BEFORE EACH ROW;
    
    AFTER EACH ROW IS BEGIN
       INSERT INTO LOG_TABLE VALUES ('AFTER EACH ROW',USER);
    END AFTER EACH ROW;
END TRIGGER1;

-- LLAMAR EL TRIGGER
INSERT INTO REGIONS VALUES (1026,'REGION COMP');
UPDATE REGIONS SET REGION_NAME = 'AAA';