/**TRIGGER DE TIPO DDL**/

-- CREAR TRIGGER
CREATE OR REPLACE TRIGGER TRIGGER_DDL 
BEFORE DROP ON HR.SCHEMA 
BEGIN
  RAISE_APPLICATION_ERROR(-20000,'NO SE PUEDEN BORRAR TABLAS');
END;

-- LLAMAR TRIGGER
DROP TABLE LOG_TABLE;