/**CURSORES - UPDATE Y DELETES CON WHERE CURRENT OF**/

DECLARE
    EMPL EMPLOYEES%ROWTYPE;
    CURSOR CUR IS SELECT * FROM EMPLOYEES FOR UPDATE;
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO EMPL;
        EXIT WHEN CUR%NOTFOUND;
        IF EMPL.COMMISSION_PCT IS NOT NULL THEN
            UPDATE EMPLOYEES SET SALARY = SALARY * 1.10 WHERE CURRENT OF CUR;
        ELSE
            UPDATE EMPLOYEES SET SALARY = SALARY * 1.15 WHERE CURRENT OF CUR;
        END IF;
    END LOOP;
    
    CLOSE CUR;
END;