/**PAQUETES PREDEFINIDOS DE ORACLE**/

-- PAQUETE UTL_FILE
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE READ_FILE IS
STRING VARCHAR2(32767);
VFILE SYS.UTL_FILE.FILE_TYPE;

BEGIN
    --OPEN FILE
    VFILE := SYS.UTL_FILE.FOPEN('EXERCISES','F1.txt','R');
    LOOP
        BEGIN
        --READ LINE
        SYS.UTL_FILE.GET_LINE(VFILE, STRING);
        DBMS_OUTPUT.PUT_LINE(STRING);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN EXIT;
        END;
    END LOOP;

    --CLOSE FILE
    SYS.UTL_FILE.FCLOSE(VFILE);
END;


--LLAMAR AL PROCEDIMIENTO

BEGIN
    READ_FILE;
END;