/**SQLCODE Y SQLERRM**/
DECLARE
    EMPL EMPLOYEES%ROWTYPE;
    CODE NUMBER;
    MESSAGE VARCHAR2(100);
BEGIN
    SELECT * INTO EMPL FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(EMPL.SALARY);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE); -- MUESTRA EL CODIGO DEL ERROR
        DBMS_OUTPUT.PUT_LINE(SQLERRM); -- MUESTRA EL MENSAGE DEL ERROR
        CODE := SQLCODE;
        MESSAGE := SQLERRM;
        INSERT INTO ERRORS VALUES (CODE,MESSAGE);
        COMMIT;
END;